set ignore-comments := true

do-the-thing:
  uv run --with requests doeverything.py

  rclone sync --checksum output/chardata ../site/static/data/chardata
  # charlist, miscdata, welcome
  rclone sync --include '*.json' --max-depth 1 --checksum output ../site/src/lib/data
  # right now any image is good enough for me
  rclone copy --ignore-existing output/images ../site/static/images

format:
  uvx ruff format *.py
